spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kindergarten?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: vniavdavadszasdfadsfdasfdasfasdvcasdvasdvdsvdsvasdvadsvdasvdvs
