name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create application.yml
        run: mkdir -p ./src/main/resources && echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Build JAR
        run: ./gradlew clean build

      - name: Debug build/libs
        run: ls -al ./build/libs

      - name: Copy JAR to Docker context
        run: cp ./build/libs/*.jar ./docker/app/app.jar

      - name: Debug docker/app
        run: ls -al ./docker/app

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kindergarten:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop kindergarten || true
            docker rm kindergarten || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/kindergarten:latest
            docker run -d --name kindergarten -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/kindergarten:latest