name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Build JAR
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ./gradlew clean build -x test -Dspring.profiles.active=production
          else
            ./gradlew clean build -x test -Dspring.profiles.active=dev
          fi

      - name: Debug build/libs
        run: ls -al ./build/libs

      - name: Copy JAR to Docker context
        run: cp ./build/libs/Kindergarten-0.0.1-SNAPSHOT.jar ./docker/app/app.jar

      - name: Debug docker/app
        run: ls -al ./docker/app

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/app
          file: ./docker/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB }}/kindergarten:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
          script: |
            sudo docker stop kindergarten || true
            sudo docker rm kindergarten || true
            sudo docker pull ${{ secrets.DOCKER_HUB }}/kindergarten:latest
            sudo docker run -d --name kindergarten -p 8080:8080 -v /home/ubuntu/logs:/home/ubuntu/logs ${{ secrets.DOCKER_HUB }}/kindergarten:latest

      - name: Deploy to Dev Server
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker stop kindergarten || true
            sudo docker rm kindergarten || true
            sudo docker pull ${{ secrets.DOCKER_HUB }}/kindergarten:dev
            sudo docker run -d --name kindergarten -p 8080:8080 -v /home/ubuntu/logs:/home/ubuntu/logs ${{ secrets.DOCKER_HUB }}/kindergarten:dev
